### ISSUE TITLE
Discord links in README no longer valid + unclear instructions on where to find the main Codex engine

### ISSUE THREAD

**Issue by kevin-niland** [Foxxyyy/CodeX.Games.RDR1#11]
Hi

The links in the README for the Discord server seem to be no longer valid. In addition to this, it's not very clear on how to actually use this application (to me, at least).

I'm assuming that there would be information on how to use this in the Discord but I would think the documentation could be improved if the instructions were included in the README.

**Comment by vStar925** [comment]
Valid discord link: https://discord.gg/BxfKHkk

You have to subscribe to the codewalker Patreon with an account linked to your discord account. After that, go to their discord and find the codex channel. Download the latest release and the files included in this repo. Copy these files into the codex folder, run the app, and in the top left corner, find the setting where you configure all your game locations. 

If you installed it right, RDR will be in that list and all you need to do is put the path to your game in that text box, then when you leave that config screen, you can now browse the game files.

**Comment by Foxxyyy** [comment]
I updated the server link but ya know there's also the link to dexyfex's Patreon if you need more details or you could just ask me on Discord instead of creating an issue for that.
