### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by mousavizare** [Foxxyyy/CodeX.Games.RDR1#15]
how to use it? there is no exe file

**Comment by Foxxyyy** [comment]
All the answers you need are in the description, it cannot be more clear.

**Comment by mousavizare** [comment]
could I replace wav files in awc files with this tool?
It was impossible with RDR Magic

**Comment by Foxxyyy** [comment]
No it cannot be done, sorry. This software has no audio support yet. It will probably come out in a few months though.

**Comment by indianaliam1** [comment]
what the guy's saying is you need to pay up for his new mod tool because there's no competitor due to the openiv guys being drove off

**Comment by Foxxyyy** [comment]
I'm not sure how to react to your message, I didn't made that software and do not gain anything from making this RDR1 project. If people aren't ready to spend 3$ to support dexyfex it is fine I don't care.

**Comment by Foxxyyy** [comment]
And unlike OpenIV everything is open-source qo feel free to fix the current issues and add the features you want.

**Comment by CabooseSayzWTF** [comment]
> what the guy's saying is you need to pay up for his new mod tool because there's no competitor due to the openiv guys being drove off

You must be very confused? Foxxyyy isn't charging anybody for anything. CodeX itself is a paid tool which was **_created by dexyfex_**. Foxxyyy just added support to CodeX to support rdr1 which he did for free. He didn't have to add support at all, and rdr1 support wouldn't be added/supported at all in CodeX

**Comment by indianaliam1** [comment]
> > what the guy's saying is you need to pay up for his new mod tool because there's no competitor due to the openiv guys being drove off
> 
> You must be very confused? Foxxyyy isn't charging anybody for anything. CodeX itself is a paid tool which was **_created by dexyfex_**. Foxxyyy just added support to CodeX to support rdr1 which he did for free. He didn't have to add support at all, and rdr1 support wouldn't be added/supported at all in CodeX

oh right thanks caboose. paid mods are still gay

**Comment by Foxxyyy** [comment]
You are gay

**Comment by Foxxyyy** [comment]
And you can't make mods
