### ISSUE TITLE
Export strtbl to xml issue

### ISSUE THREAD

**Issue by michalss** [Foxxyyy/CodeX.Games.RDR1#16]
Hi,

There is nasty bug to export/import strtbl files to xml. For example file **graveyards_win32.strtbl**

To be exact, export is possible but its giving me wrong xml file and it cannot be reimporetd back.

```
 <Item type="String" key="ofg9_0"><fs3>May she rest in peace<nl>with God</Item>
```

this is not valid for xml

There is mssing replacement of chars like < > etc.. with 

```
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&apos;'
```

**Comment by Foxxyyy** [comment]
Issue fixed in the last update
