### ISSUE TITLE
Help: How to load a loose file.

### ISSUE THREAD

**Issue by Hancapo** [Foxxyyy/CodeX.Games.RDR1#6]
I'm trying to load a `.wvd` directly from a folder, I tried many things, but I couldn't get it working.

The current code:
```csharp
WvdFile wvdFile = new WvdFile();
Stream s = new FileStream("agv_barn01x.wvd", FileMode.Open);
BinaryReader br = new BinaryReader(s);
Rpf6Entry something = Rpf6Entry.ReadEntry(null, br);

wvdFile.Load(br.ReadBytes((int)br.BaseStream.Length));
```

**Comment by Foxxyyy** [comment]
That can't really be done since resources are meant to be stored inside RPF files sorry.
If you only have one or a few files you can try loading them from a RPF.

**Comment by Foxxyyy** [comment]
So I managed to modify the code a bit to handle errors and to load resources from outside an RPF.

The thing is the WVD files relies on the directory they are stored to load some missing textures.

As you can see textures are messed up. you shouldn't get too much issues for fragments and other models though if you need to use those.

Just DM me on Discord if you need the code #imfoxxyyy

![Capture d'écran 2024-11-01 110642](https://github.com/user-attachments/assets/e86264f3-b386-4202-8da4-43a7304614c9)
![Capture d'écran 2024-11-01 111733](https://github.com/user-attachments/assets/30a7f647-e741-4d52-a3b6-256605ad004f)
