### ISSUE TITLE
It only wants GTA V

### ISSUE THREAD

**Issue by RyanDavanzo** [Foxxyyy/CodeX.Games.RDR1#9]
I pasted the files into the CodeWalker folder, but it only asks for the GTAV.exe. Renaming the RDR.exe just crashes it.

**Comment by vStar925** [comment]
You need codex, not codewalker. You need to join their discord and it cost $3.

**Comment by TheSteelStallion** [comment]
> You need codex, not codewalker. You need to join their discord and it cost $3.

See, that's where I'm having an issue here. I've been recommended CodeX from the GTAForums and was told about it. Upon buying a membership, I'm having trouble locating this "codex" on their discord. Everything on there from my end is referring to codewalker only with no sign of codex anywhere. Unless I'm missing something obvious, there's no codex channel in sight, which is what Dexy said there would be.

**Comment by vStar925** [comment]
Make sure your patreon is linked to your discord so you get access to the channel. Once it is, I think the channel is called codex or codex-releases. It's toward the top.

**Comment by TheSteelStallion** [comment]
> Make sure your patreon is linked to your discord so you get access to the channel. Once it is, I think the channel is called codex or codex-releases. It's toward the top.

Oh you absolute beauty, thank you so very much. It took some confusing account linkage between apps but I see it now. Far more instructive than the actual instructions!
